# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ish-yzK4hp3JMtiYJA6-Fr-d8AaLbQ8J
"""

import streamlit as st
import os
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from PIL import Image
from ultralytics import YOLO
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate

# --- 1. CONFIGURATION & STYLING ---
st.set_page_config(page_title="AI Safety Sentinel Pro", layout="wide", page_icon="🛡️")
# API Key'ini güncelledim (Eski hata veren model ismini de düzelttim)
os.environ["GOOGLE_API_KEY"] = "AIzaSyBpvW-bE6-LXKuf-VDf88Oy5sFF_8obi8w"

st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    </style>
    """, unsafe_allow_html=True)

# --- 2. DATABASE INIT ---
DB_PATH = "safety_master_v3.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    conn.execute('''CREATE TABLE IF NOT EXISTS logs
                    (id INTEGER PRIMARY KEY AUTOINCREMENT,
                     camera_id TEXT, violation_count INTEGER,
                     total_persons INTEGER, violation_rate REAL,
                     status TEXT, timestamp DATETIME)''')
    conn.close()

init_db()

@st.cache_resource
def load_yolo():
    return YOLO('best.pt')

# --- 3. SIDEBAR (CONTROL PANEL) ---
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/1063/1063302.png", width=100)
    st.title("Control Panel")
    camera_id = st.selectbox("📹 Select Monitoring Point", ["Camera 1 (Office)", "Camera 2 (Construction)"])
    uploaded_file = st.file_uploader("📂 Upload Site Image", type=['jpg', 'jpeg', 'png'])

# --- 4. SAFETY RULES & MULTI-AGENT PROMPTS ---
safety_regulations_db = """
HSE GLOBAL PROTOCOLS:
- ZONE [Camera 2 - Construction]:
  * helmet_off: CRITICAL VIOLATION. Penalty: 1000 USD fine.
  * Action: Immediate suspension of duties.
- ZONE [Camera 1 - Office/Break]:
  * helmet_off: PERMITTED. Penalty: None.
  * Action: No disciplinary action.
"""

# Ajan 1: Sert Denetçi
strict_prompt = PromptTemplate.from_template("""
Role: Strict HSE Auditor.
Your goal is 100% compliance. If there is a violation in {camera_id}, demand the maximum penalty according to:
{regulations}
Detections: {v_count} violations out of {t_count} people.
Historical Trend: %{avg_history:.1f}.
Write a short, harsh enforcement recommendation.
""")

# Ajan 2: Empatik Koç
coach_prompt = PromptTemplate.from_template("""
Role: HSE Safety Coach.
Your goal is long-term safety culture. Instead of just fines, suggest training or root-cause analysis.
Context: {camera_id} | Violations: {v_count}/{t_count}.
Regulations: {regulations}
Write a supportive, education-oriented recommendation.
""")

# Ajan 3: Nihai Karar Verici (Consensus)
judge_prompt = PromptTemplate.from_template("""
Role: Senior HSE Director.
You have received two conflicting reports regarding an incident at {camera_id}.
Strict Auditor says: {strict_report}
Safety Coach says: {coach_report}

Detections: {v_count} violations, {t_count} people.
Final Decision Task: Create a balanced, professional 'Final Verdict' that ensures safety but remains fair.
Use a 3-section format: Summary, Findings, Final Action Plan.
Language: English.
""")

# --- 5. CORE ANALYSIS LOGIC ---
if uploaded_file:
    with open("temp.jpg", "wb") as f:
        f.write(uploaded_file.getbuffer())

    model = load_yolo()
    results = model.predict(source="temp.jpg", conf=0.25, verbose=False)

    v_cnt, t_p = 0, 0
    detections_list = []
    res_plotted = results[0].plot()
    for r in results:
        for box in r.boxes:
            t_p += 1
            label = model.names[int(box.cls)]
            detections_list.append(label)
            if label == 'helmet_off': v_cnt += 1

    v_rate = (v_cnt / t_p * 100) if t_p > 0 else 0
    detection_summary = ", ".join(detections_list) if detections_list else "No people detected."

    # History for Agent
    conn = sqlite3.connect(DB_PATH)
    df_temp = pd.read_sql_query(f"SELECT violation_rate FROM logs WHERE camera_id='{camera_id}' AND status='APPROVED'", conn)
    avg_history = df_temp['violation_rate'].tail(5).mean() if not df_temp.empty else 0

    # UI Metrics
    col_m1, col_m2, col_m3 = st.columns(3)
    col_m1.metric("Total People", t_p)
    col_m2.metric("Violations", v_cnt)
    col_m3.metric("AI Risk Assessment", f"%{v_rate:.1f}")

    # Display AI Feed and Multi-Agent Discussion
    col_left, col_right = st.columns([1.2, 1])
    with col_left:
        st.subheader("🖼️ AI Visual Detection Feed")
        st.image(res_plotted, channels="BGR", use_column_width=True)

    with col_right:
        st.subheader("🤖 Multi-Agent Consensus Report")
        llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.2)

        with st.spinner("Agents are debating the incident..."):
            # 1. Sert Ajan Görüşü
            s_report = (strict_prompt | llm).invoke({
                "camera_id": camera_id, "regulations": safety_regulations_db,
                "v_count": v_cnt, "t_count": t_p, "avg_history": avg_history
            })

            # 2. Empatik Ajan Görüşü
            c_report = (coach_prompt | llm).invoke({
                "camera_id": camera_id, "regulations": safety_regulations_db,
                "v_count": v_cnt, "t_count": t_p
            })

            # 3. Nihai Karar (Judge)
            final_verdict = (judge_prompt | llm).invoke({
                "camera_id": camera_id, "strict_report": s_report.content,
                "coach_report": c_report.content, "v_count": v_cnt, "t_count": t_p
            })

            st.markdown(final_verdict.content)

        # BUTON: Analizi Onay Sırasına Gönder
        if st.button("📥 SUBMIT ANALYSIS TO REVIEW QUEUE"):
            conn.execute("INSERT INTO logs (camera_id, violation_count, total_persons, violation_rate, status, timestamp) VALUES (?, ?, ?, ?, ?, ?)",
                         (camera_id, v_cnt, t_p, v_rate, "PENDING", datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
            conn.commit()
            st.success("Successfully sent to human review queue!")
    conn.close()

# --- 6. REVIEW QUEUE & AGENT REPORTING (HUMAN-IN-THE-LOOP) ---
st.divider()
st.header("👨‍✈️ Auditor Review Panel")

conn = sqlite3.connect(DB_PATH)
pending_logs = pd.read_sql_query("SELECT * FROM logs WHERE status = 'PENDING'", conn)

if not pending_logs.empty:
    for idx, row in pending_logs.iterrows():
        with st.expander(f"Review Required: ID {row['id']} | {row['camera_id']} | {row['timestamp']}"):
            c1, c2 = st.columns([1, 1])

            with c1:
                st.write(f"**AI Detection Summary:** {row['violation_count']} violations found.")
                if st.button("✅ APPROVE & LOG", key=f"a_{row['id']}"):
                    conn.execute("UPDATE logs SET status = 'APPROVED' WHERE id = ?", (row['id'],))
                    conn.commit()
                    st.rerun()
                if st.button("❌ REJECT / IGNORE", key=f"r_{row['id']}"):
                    conn.execute("UPDATE logs SET status = 'REJECTED' WHERE id = ?", (row['id'],))
                    conn.commit()
                    st.rerun()

            with c2:
                st.info("The agents above have reached a consensus. Review their verdict before approving.")
else:
    st.info("The review queue is currently empty.")

# --- 7. FINAL ANALYTICS ---
st.divider()
st.header("📊 Verified Safety Analytics Dashboard")
approved_df = pd.read_sql_query(f"SELECT * FROM logs WHERE status = 'APPROVED' AND camera_id = '{camera_id}'", conn)

if not approved_df.empty:
    cur_avg = approved_df['violation_rate'].tail(5).mean()
    if cur_avg > 30:
        st.error(f"🚨 SYSTEMIC FAILURE: Historical violation rate is %{cur_avg:.1f}! Training Mandatory.")

    col_g1, col_g2 = st.columns(2)
    with col_g1:
        st.subheader("Violation Count History")
        st.line_chart(approved_df.set_index('timestamp')['violation_count'])
    with col_g2:
        st.subheader("Risk Percentage Trend")
        st.line_chart(approved_df.set_index('timestamp')['violation_rate'])

    st.table(approved_df[['timestamp', 'violation_count', 'total_persons', 'violation_rate']].tail(5))

conn.close()